### PR TITLE
Ignore unsorted imports in __init__.py

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by sbidoul** [comment]
Why does the order of imports matter?

**Comment by adrienpeiffer** [comment]
In some cases, order is important for registry loading.
Typically, if a model inherits from a new model defined in the same module, the new model must be imported first.

**Comment by adrienpeiffer** [comment]
Models are loaded by the order given in the init file.
https://github.com/odoo/odoo/blob/6bb16bf8818042b05ff8d40f852fa8e7d9eba92f/odoo/modules/registry.py#L245

**Comment by sbidoul** [comment]
Yes. Another thing that would be resolved with typodoo :stuck_out_tongue:

**Pull request merged**
